---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install KDE Connect
  ansible.builtin.apt:
    name: kdeconnect
    state: present

- name: Display KDE Connect installation message
  ansible.builtin.debug:
    msg:
      - "KDE Connect has been successfully installed!"
