---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install VLC
  ansible.builtin.apt:
    name: vlc
    state: present

- name: Display VLC installation message
  ansible.builtin.debug:
    msg:
      - "VLC has been successfully installed!"
