---
# Targets inventory hosts (use default inventory for localhost, or -i '<ip>,' from Terraform local_exec).
- name: Setup Ubuntu with required software
  hosts: all
  become: true

  roles:
    - network-utils
    - utilities
    - awscli
    - rclone
    - ghcli
    - zerotier
    - fonts
    - docker
    - caddy
    # - mongodb-tools
    - shell
    - ufw
